I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
Traceback (most recent call last):
  File "network.py", line 381, in <module>
    network = Network(model, **cargs)
  File "network.py", line 82, in __init__
    self._validset = Dataset(self.valid_file, self._vocabs, model, self._config, name='Validset')
  File "/disk/ocean/rcardenas/dep-par-biaffine/dataset.py", line 55, in __init__
    self.rebucket()
  File "/disk/ocean/rcardenas/dep-par-biaffine/dataset.py", line 159, in rebucket
    buff = self._file_iterator.next()
  File "/disk/ocean/rcardenas/dep-par-biaffine/dataset.py", line 102, in file_iterator
    buff = self._process_buff(buff)
  File "/disk/ocean/rcardenas/dep-par-biaffine/dataset.py", line 126, in _process_buff
    tid = (tags.PUNCT,) if test_punct(word[:-3]) else (tags.UNK,) # assumes token is <word>_<langid>
  File "/disk/ocean/rcardenas/dep-par-biaffine/dataset.py", line 37, in test_punct
    if unicodedata.category(unicode(c))[0] != 'P':
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
